# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  dockerRegistryServiceConnection: "3c4c2f91-df8f-41d2-9e6e-1892620a9391"
  imageRepository: "intentory-app"
  containerRegistry: "joseleonc.azurecr.io"
  dockerfilePath: "$(Build.SourcesDirectory)/Dockerfile"
  tag: "$(Build.BuildId)"

  vmImageName: "ubuntu-latest"
  azureSubscriptionConnection: "MyAzureSubscriptionConnection"
  environmentName: "Production"

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest   # still pushed for convenience, but not used in deploy

  - stage: Deploy
    displayName: Deploy to Azure
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployJob
        displayName: Deploy Container
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureContainerApps@1
                  displayName: Deploy to Azure Container Apps
                  inputs:
                    azureSubscription: $(azureSubscriptionConnection)
                    containerAppName: "intentory-app"
                    resourceGroup: "test-resource-group"
                    imageToDeploy: $(containerRegistry)/$(imageRepository):$(tag) # <-- uses BuildId tag
